name: Go

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      firestore:
        image: google/cloud-sdk
        ports:
          - 8000:8000
        options: -ti

    env:
      GO111MODULE: on
      FIRESTORE_EMULATOR_HOST: 127.0.0.1:8000

    steps:
      - name: Install firestore emulator
        run: docker exec $(docker ps -f "ancestor=google/cloud-sdk" -q) apt install -y google-cloud-sdk-firestore-emulator
      - name: Start firestore emulator
        run: docker exec -d $(docker ps -f "ancestor=google/cloud-sdk" -q) gcloud beta emulators firestore start --project=pname --host-port 0.0.0.0:8000

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - uses: actions/checkout@v3

      - name: Ensure samples are generated
        env:
          TZ: Asia/Tokyo
        run: |
          export PATH=$PATH:$PWD/bin
          make gen_samples
          
          clean=$(git status | grep "nothing to commit" || true)
          if [ -z "$clean" ]; then
            git diff
            echo 'Please run "make gen_samples"'
            exit 1
          fi

      - name: Run tests
        run: |
          make test TEST_OPT='-tags="emulator"'
